default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>

development:
  <<: *default
  database: lifeboard_development

test:
  <<: *default
  database: lifeboard_test

production:
  <<: *default
  database: lifeboard_production
  username: lifeboard
  password: <%= ENV['LIFEBOARD_DATABASE_PASSWORD'] %>
